=== BenediktNiehues/org.eclipse.xpand/examples/org.eclipse.xpand.examples.xsd.m2m.xml2svg/src/xsd/m2m/xml2svg/loadcurve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/loadcurve"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.example.org/loadcurve">

	<complexType name="LoadCurve">
		<sequence>
			<element name="Name" type="string" />
			<element name="Description" type="string" />
			<element name="CreationDate" type="dateTime" />
			<element name="StartTime" type="dateTime" />
			<element name="Measurement" type="tns:Measurement"
				maxOccurs="unbounded" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="Measurement">
		<attribute name="Time" type="int" />
		<attribute name="Value" type="float" />
	</complexType>

	<element name="LoadCurve" type="tns:LoadCurve"></element>
</schema>

=== BenediktNiehues/org.eclipse.xpand/examples/org.eclipse.xpand.examples.xsd.m2m.xml2svg/src/xsd/m2m/xml2svg/mycurve.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:LoadCurve xmlns:tns="http://www.example.org/loadcurve"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/loadcurve loadcurve.xsd ">
	<tns:Name>My Custom Load Curve</tns:Name>
	<tns:Description>
		This load curve has been transformed from custom XML to SVG.
	</tns:Description>
	<tns:CreationDate>2001-12-31T12:00:00</tns:CreationDate>
	<tns:StartTime>2001-12-31T12:00:00</tns:StartTime>
	<tns:Measurement Time="0" Value="0.0" />
	<tns:Measurement Time="4" Value="10.0" />
	<tns:Measurement Time="7" Value="5.0" />
	<tns:Measurement Time="10" Value="67.0" />
	<tns:Measurement Time="15" Value="12.0" />
	<tns:Measurement Time="20" Value="45.0" />
	<tns:Measurement Time="21" Value="23.0" />
	<tns:Measurement Time="22" Value="30.0" />
	<tns:Measurement Time="30" Value="28.0" />
	<tns:Measurement Time="35" Value="35.0" />
</tns:LoadCurve>

=== BenediktNiehues/org.eclipse.xpand/examples/org.eclipse.xpand.examples.xsd.m2t.genmodel/src/xsd/m2t/genmodel/mycurve.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:LoadCurve xmlns:tns="http://www.example.org/loadcurve" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/loadcurve loadcurve.xsd ">
  <tns:Name>My Simple Loadcurve</tns:Name>
  <tns:Description>This is a really long description for a curve</tns:Description>
  <tns:CreationDate>2001-12-31T12:00:00</tns:CreationDate>
  <tns:StartTime>2001-12-31T12:00:00</tns:StartTime>
  <tns:Measurement Time="0" Value="0.0"/>
  <tns:Measurement Time="1" Value="3.0"/>
  <tns:Measurement Time="2" Value="5.7"/>
  <tns:Measurement Time="5" Value="1.2"/>
</tns:LoadCurve>
