=== BenediktNiehues/org.eclipse.xpand/examples/org.eclipse.xpand.examples.xsd.m2t.xml2javawizard/src/xsd/m2t/xml2javawizard/wizard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/wizard" elementFormDefault="qualified" targetNamespace="http://www.example.org/wizard">

	<complexType name="Wizard">
		<sequence>
			<element name="startpage" type="IDREF"/>
			<element name="name" type="string"/>
			<element name="welcometext" type="string"/>
			<element maxOccurs="unbounded" minOccurs="0" name="optionpage" type="tns:OptionPage"/>
			<element maxOccurs="unbounded" minOccurs="0" name="choicepage" type="tns:ChoicePage"/>
			<element maxOccurs="unbounded" minOccurs="0" name="finalpage" type="tns:FinalPage"/>
		</sequence>
	</complexType>

	<complexType name="AbstractPage">
		<sequence>
			<element name="title" type="string"/>
		</sequence>
		<attribute name="id" type="ID"/>
	</complexType>

	<complexType name="OptionPage">
		<complexContent>
			<extension base="tns:AbstractPage">
				<sequence>
					<element maxOccurs="unbounded" minOccurs="1" name="option" type="string"/>
					<element name="nextpage" type="IDREF"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ChoicePage">
		<complexContent>
			<extension base="tns:AbstractPage">
				<sequence>
					<element maxOccurs="unbounded" minOccurs="1" name="choice">
						<complexType>
							<attribute name="title" type="string"/>
							<attribute name="target" type="IDREF"/>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="FinalPage">
		<complexContent>
			<extension base="tns:AbstractPage">
				<sequence>
					<element name="text" type="string"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<element name="wizard" type="tns:Wizard"/>
</schema>

=== BenediktNiehues/org.eclipse.xpand/examples/org.eclipse.xpand.examples.xsd.m2t.xml2javawizard/src/xsd/m2t/xml2javawizard/mysetup.xml
<?xml version="1.0" encoding="UTF-8"?>
<wizard xmlns="http://www.example.org/wizard"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/wizard wizard.xsd ">
	<startpage>start</startpage>
	<name>My Example Setup</name>
	<welcometext>Welcome to this little demo application.</welcometext>

	<optionpage id="license">
		<title>Please enter your license code.</title>
		<option>Surname</option>
		<option>Given name</option>
		<option>License Code</option>
		<nextpage>path</nextpage>
	</optionpage>

	<optionpage id="path">
		<title>Please enter the target path on your hard drive.</title>
		<option>Target Path</option>
		<nextpage>final</nextpage>
	</optionpage>

	<choicepage id="start">
		<title>Please choose your preferred version.</title>
		<choice title="Install Full Version" target="license" />
		<choice title="Demo Version" target="path"/>
		<choice title="Cancel. Don't install anything." target="cancel"/>
	</choicepage>

	<finalpage id="final">
		<title>Done.</title>
		<text>Thank you for choosing our product.</text>
	</finalpage>

	<finalpage id="cancel">
		<title>Setup Canceled</title>
		<text>Please try us again at some point, anyway.</text>
	</finalpage>

</wizard>
